<a href="https://colab.research.google.com/github/CiroAlfa/Hi-new-world/blob/main/Copia_de_Dimensiones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [ ]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [ ]:
matriz= np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

el numero dos fuera del parentesis representa cuantas dimensiones estamos manejando

In [ ]:
tensor= np.array([[[1,2,3],[4,5,6],[7,5,6,],[4,5,6]],[[1,2,3],[4,5,6],[7,5,6,],[4,5,6]]])
print(tensor)
tensor.ndim

[[[1 2 3]
  [4 5 6]
  [7 5 6]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [7 5 6]
  [4 5 6]]]


3

el parametro mdim nos indica cuantas dimensiones estamos manejando

Agregar o eliminar dimensiones

In [ ]:
vector = np.array([1,2,3], ndmin=10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

ndim nos crea nuevas dimensiones las que e pidamos

In [ ]:
expand = np.expand_dims(np.array([1,2,3]),axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

expand nos agrega tambien nueva dimension

squeeze nos deja solo las dimensiones necesarias

In [ ]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1
