<a href="https://colab.research.google.com/github/CiroAlfa/Hi-new-world/blob/main/Copia_de_creando_arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

del 0 al 20 de dos en dos

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
np.ones((10,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [ ]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

algebra lineal se usa mucho  eye

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.random.rand(4)

array([0.10019686, 0.48917784, 0.58959771, 0.99851128])

In [ ]:
np.random.rand(4,4)

array([[0.66039235, 0.53505169, 0.10570105, 0.25907503],
       [0.33795118, 0.12416243, 0.53446862, 0.87431561],
       [0.94786174, 0.81254366, 0.0183975 , 0.94909428],
       [0.02485001, 0.19971989, 0.80471809, 0.49584856]])

In [ ]:
np.random.randint(1,15)

10

In [ ]:
np.random.randint(1,100,(10,10))

array([[12, 12, 19, 91, 63, 44, 43, 21, 17, 61],
       [61, 56, 61,  9, 46, 23, 16, 86, 90, 63],
       [76, 49, 60, 78, 51,  2, 37, 62, 28,  7],
       [44,  9, 12, 15, 96, 93, 36, 37, 57, 87],
       [47, 18, 11, 82,  5, 49, 96, 63, 75, 87],
       [98,  6, 33, 60, 15, 35, 11,  8, 66, 59],
       [42, 92, 17,  1, 54, 43,  1,  5, 62, 10],
       [59, 97,  8, 39, 44, 54, 67, 84, 18, 53],
       [34, 67, 47, 31, 28, 42, 50, 95, 20, 94],
       [39, 29, 97, 91, 24,  3, 68, 33, 85, 89]])