<a href="https://colab.research.google.com/github/CiroAlfa/Hi-new-world/blob/main/Copia_de_conditions%26operaciones.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
 arr = np.linspace(1,10,10, dtype='int8')
 arr


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
indices_cond = arr>5
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_cond]
#arr[arr>5]


array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(indices_cond) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr>5]=99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

OPERACIONES

In [ ]:
lista = [1,2]
lista

[1, 2]

In [ ]:
lista*2

[1, 2, 1, 2]

In [ ]:
arr = np.arange(0,10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr = np.arange(0,10)
arr2 = arr.copy()

operations

In [ ]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr*2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr+2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
1/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in true_divide
  """Entry point for launching an IPython kernel.


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr**2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr / arr2

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
matriz = arr.reshape(2,5)
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [ ]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [ ]:
np.matmul(matriz, matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz2.T

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])