<a href="https://colab.research.google.com/github/CiroAlfa/Hi-new-world/blob/main/Copia_de_Untitled1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
lista =[1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr=np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz= [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
1

1

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]

1

In [ ]:
arr[0]+ arr[5]

7

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[0,2]

3

In [ ]:
arr[0:3]

array([1, 2, 3])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [ ]:
arr[:6]

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr[2:]

array([3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[::3]

array([1, 4, 7])

In [ ]:
arr[-1]

9

In [ ]:
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz[2,0:3]

array([7, 8, 9])

In [ ]:
np.arr = np.array([1,2,3,4])
arr.dtype

dtype('int64')

In [ ]:
np.arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('int64')

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr.astype(np.float64)

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
arr = np.array([0,1,2,3,4])
arr= arr.astype(np.bool_)
arr

array([False,  True,  True,  True,  True])

In [ ]:
arr = np.array([0,1,2,3,4])
arr= arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array([0,1,2,3,4])
arr= arr.astype(np.string_)
arr

array([b'0', b'1', b'2', b'3', b'4'], dtype='|S21')

In [ ]:
arr = np.array([0,1,2,3,4])
arr= arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

DIMENSIONES VECTOR

3 dimensiones

solo se puede usar un único tipo de dato