<a href="https://colab.research.google.com/github/CiroAlfa/Hi-new-world/blob/main/funciones_principales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr = np.random.randint(1,20,10)

In [3]:
matriz=arr.reshape(2,5)
matriz

array([[ 7, 10, 19,  6, 10],
       [ 5,  1,  6, 10,  8]])

In [4]:
arr


array([ 7, 10, 19,  6, 10,  5,  1,  6, 10,  8])

In [5]:
arr.max()

19

In [6]:
matriz

array([[ 7, 10, 19,  6, 10],
       [ 5,  1,  6, 10,  8]])

In [7]:
matriz.max(1)

array([19, 10])

In [8]:
matriz.max(0)

array([ 7, 10, 19, 10, 10])

argmax muestra el indice en donde se encuentra el valor mas grande de nuestro array

In [9]:
arr.argmax()

2

In [13]:
matriz.argmax(0)

array([0, 0, 0, 1, 0])

In [18]:
matriz

array([[ 7, 10, 19,  6, 10],
       [ 5,  1,  6, 10,  8]])

In [11]:
matriz.max(0)

array([ 7, 10, 19, 10, 10])

In [14]:
arr.min()

1

In [15]:
matriz.min(0)


array([5, 1, 6, 6, 8])

In [16]:
arr.argmin()

6

In [19]:
matriz

array([[ 7, 10, 19,  6, 10],
       [ 5,  1,  6, 10,  8]])

In [17]:
matriz.argmin(1)

array([3, 1])

In [20]:
arr

array([ 7, 10, 19,  6, 10,  5,  1,  6, 10,  8])

In [21]:
arr.ptp()

18

In [22]:
matriz.ptp(0)

array([ 2,  9, 13,  4,  2])

In [ ]:
np.percentile es la mitad de los numeros del centro sumados y divididos en 2 en este caso 10+5/2 = 7.5

In [24]:
arr

array([ 7, 10, 19,  6, 10,  5,  1,  6, 10,  8])

In [23]:
np.percentile(arr,50)

7.5

In [25]:
arr.sort()
arr

array([ 1,  5,  6,  6,  7,  8, 10, 10, 10, 19])

In [26]:
np.percentile(arr,50)

7.5

In [27]:
np.median(arr)

7.5

In [28]:
np.median(matriz,1)

array([ 6., 10.])

In [29]:
np.std(arr)

4.467661580737736

In [30]:
np.var(arr)

19.96

In [ ]:
es la media la suma de todos los valores dividido por la cantidad de valores

In [31]:
np.mean(arr)

8.2

In [61]:
a= np.array([[1,2],[3,4]])
b= np.array([5,6])

queremos concatenar los dos array

In [62]:
np.concatenate((a,b),axis=0)

ValueError: ignored

el error fue por que estaba en dimensiones diferentes

In [63]:
a.ndim
b.ndim

1

el siguiente es el mismo código de la celda 33 pero como ya gestionamos bien el tema de las dimensiones es decir lo pusimos en la misma dimension ahora si funciona

In [64]:
b = np.expand_dims(b,axis=0)

In [65]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [66]:
# np.concatenate((a,b),axis=1)

ValueError: ignored

In [ ]:
# concatenamos usando la T transpuesta de una matriz tenamos una forma 3 * 2 y ahora es 2* 3

In [68]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])